name: Refuse update on journalList.csv

on:
  push:
    paths:
      - 'src/main/resources/journals/journalList.csv'

jobs:
  refuse:
    name: Comment
    runs-on: ubuntu-latest
    steps:
      - name: comment PR
        uses: unsplash/comment-on-pr@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          msg: "Please do not update journalList.csv directly. Please update the list at <https://github.com/JabRef/abbrv.jabref.org/tree/master/journals>"
